# Generated by Django 2.2.10 on 2021-11-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poles_app', '0002_auto_20211111_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
    ]
