# Generated by Django 2.2.10 on 2021-11-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poles_app', '0003_remove_answer_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='user_id',
        ),
    ]
